### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by demlak** [mauricerenck/rate-page#10]
v1.1.2
on clicking a star (planet) on rating, console says:
```
stars.js:31 POST https://..../rate-page/stars 404 (Not Found)
sendRating @ stars.js:31
(anonymous) @ stars.js:113
```

**Comment by mauricerenck** [comment]
Can you please provide the full url, I cannot reproduce this behavior on my test installations. Thank you.

**Comment by demlak** [comment]
Fresh install of kirby starterkit 3.5.1 with ratepage v1.1.2.
only edit of starterkit is: css added to head.php, stars-snippet added to note.php

https://wohnwelt-wunstorf.de/starterkit-master/notes/exploring-the-universe

**Comment by mauricerenck** [comment]
This was caused because you installed kirby in a subfolder not in the domain root. I had to adapt the urls for this to work. Fixed in 1.1.3

**Comment by demlak** [comment]
thx.. i just installed a new fresh install.. there is still a 404 with v1.1.3
https://wohnwelt-wunstorf.de/sk/notes/exploring-the-universe

**Comment by mauricerenck** [comment]
I am on it. 
The URLs are okay, the routes should be firing, but as soon as kirby is installed in a subfolder the routes don't work.

**Comment by mauricerenck** [comment]
I had to rewrite the whole thing to get it working with kirby installed in subfolders. You should be able to use v1.2.0.

**Comment by demlak** [comment]
nice!
this issue seems to be fixed.. thx a very lot!
