### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by muppet922** [mauricerenck/rate-page#15]
Hello, I have the following issue =>
`Parse error: syntax error, unexpected ''enable-webmention-support'' (T_CONSTANT_ENCAPSED_STRING), expecting ']' in E:\xampp\htdocs\site\config\config.php on line 7`

My config.php =>
```
<?php

return [
    'debug'  => true,
    'thumb-up-symbol' => '👍',
    'thumb-down-symbol' => '👎'
    'enable-webmention-support' => false
    'stars.symbol-empty' => '🌑',
    'stars.round' => true,
    'stars.showAvg' => true,
];`

```

What should I do? thanks in advance and have a nice day.

**Comment by mauricerenck** [comment]
Hey,
every config setting must end with a comma, thumb-down-symbol and enable-webmention-support ist missing the `,` at the end of the line. You also have to prepend the plugin path. I have missed that in the example. This is, how it should look like:

```
<?php

return [
    'mauricerenck.ratePage.debug'  => true,
    'mauricerenck.ratePage.thumb-up-symbol' => '👍',
    'mauricerenck.ratePage.thumb-down-symbol' => '👎',
    'mauricerenck.ratePage.enable-webmention-support' => false,
    'mauricerenck.ratePage.stars.symbol-empty' => '🌑',
    'mauricerenck.ratePage.stars.round' => true,
    'mauricerenck.ratePage.stars.showAvg' => true,
];
```

Those values above are the default values, you only need to set one of them, if you want to overwrite the default value.

**Comment by muppet922** [comment]
Thanks, now it's working. In your readme from this repository the commas are missing, misleading a little :D. Thanks man, have a nice day.
