### ISSUE TITLE
Multisite-support

### ISSUE THREAD

**Issue by demlak** [mauricerenck/rate-page#3]
Hey.. i'm not very familiar with git/github.. so i add an issue for a code-suggestion (i have to learn this pull request thingy):

you use `hardcoded` links to css and js files.. on mulitsite setups, this results in wrong URLs.

Better use 
`kirby()->url('media') . '/plugins/mauricerenck/ratePage/...`
instead of
`/media/plugins/mauricerenck/ratePage/...`

regards

**Comment by mauricerenck** [comment]
thank you for the hint, I will change that.
