### ISSUE TITLE
v1.1.0 kills kirby complete

### ISSUE THREAD

**Issue by demlak** [mauricerenck/rate-page#4]
Hey.. i just tried the new 1.1.0 and kirby is destroyed when plugin is copied to plugin-folder =)
i can't see anything... just a blank page.. also on panel.

problem seems to be something with the autoload thing. i tried to comment everything one after the other in the index.php at if i comment `/* @include_once __DIR__ . '/vendor/autoload.php'; */`, website is able to load again.

**Comment by mauricerenck** [comment]
This should be fixed with 1.1.1 can you please confirm that?

**Comment by demlak** [comment]
now it loads..
